### ISSUE TITLE
Invalid field error for 'analytic_account_id'

### ISSUE THREAD

**Issue by bennals** [OCA/mis-builder-contrib#21]
## Module
mis-builder-analytic

## Describe the bug
After following the usage instructions and setting 'Actuals (alternative)' on the 'Source' field, 'MIS Account Analytic Line' on the 'Move lines source' field, and setting an analytic filer, either on a column or the report as a whole, I get the following error after clicking preview:

Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo-server/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 935, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 927, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-server/odoo/api.py", line 699, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo-server/odoo/api.py", line 690, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/thirdparty/addons/mis_builder/models/mis_report_instance.py", line 817, in compute
    kpi_matrix = self._compute_matrix()
  File "/home/odoo/thirdparty/addons/mis_builder/models/mis_report_instance.py", line 810, in _compute_matrix
    self._add_column(aep, kpi_matrix, period, period.name, description)
  File "/home/odoo/thirdparty/addons/mis_builder_budget/models/mis_report_instance.py", line 85, in _add_column
    aep, kpi_matrix, period, label, description
  File "/home/odoo/thirdparty/addons/mis_builder/models/mis_report_instance.py", line 782, in _add_column
    aep, kpi_matrix, period, label, description
  File "/home/odoo/thirdparty/addons/mis_builder/models/mis_report_instance.py", line 754, in _add_column_move_lines
    no_auto_expand_accounts=self.no_auto_expand_accounts,
  File "/home/odoo/thirdparty/addons/mis_builder/models/mis_report.py", line 887, in _declare_and_compute_period
    expression_evaluator.aep_do_queries()
  File "/home/odoo/thirdparty/addons/mis_builder/models/expression_evaluator.py", line 37, in aep_do_queries
    self.aml_model,
  File "/home/odoo/thirdparty/addons/mis_builder/models/aep.py", line 353, in do_queries
    lazy=False,
  File "/home/odoo/odoo-server/odoo/models.py", line 1944, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/odoo/odoo-server/odoo/models.py", line 1967, in _read_group_raw
    query = self._where_calc(domain)
  File "/home/odoo/odoo-server/odoo/models.py", line 3643, in _where_calc
    e = expression.expression(domain, self)
  File "/home/odoo/odoo-server/odoo/osv/expression.py", line 669, in __init__
    self.parse()
  File "/home/odoo/odoo-server/odoo/osv/expression.py", line 847, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'analytic_account_id' in leaf "<osv.ExtendedLeaf: ('analytic_account_id', '=', 3519) on mis_account_analytic_line (ctx: )>"

**Affected versions**:
11.0

**Expected behavior**
The report to display without errors

**Additional context**
I'm using account_analytic_parent, account_analytic_distribution, account_analytic_required and account_analytic_distribution_required (all OCA modules) as well.  Don't have any other problems using analytic accounting and I use it extensively

**Comment by bennals** [comment]
Just got the exact same error on runboat with a freshly created analytic account/template/report

![Screen Shot 2022-05-23 at 5 55 18 pm](https://user-images.githubusercontent.com/7786180/169771429-a3de773c-0efa-4672-b835-80119f1c9ed3.png)
